name: zmovies
description: ZMoviesFlutter is an example app that built with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # for model
  freezed_annotation: ^1.1.0
  
  # for network
  dio: ^4.0.4
  retrofit: ^3.0.1

  # for state management/routing/dependencies management
  get: ^4.6.1
  
  # for local k-v storage
  shared_preferences: ^2.0.12

  # for image ui
  cached_network_image: ^3.2.0
  
dev_dependencies:
  # for unit test
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  
  # for analyzing  
  flutter_lints: ^1.0.0
  lints: ^1.0.1
  
  # for model
  freezed: ^1.1.1
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4

  # for generating launcher logo
  flutter_launcher_icons: ^0.9.2

  # for generating assets object
  flutter_gen_runner: ^4.1.5
  

flutter:
  # for material design icons & fonts
  uses-material-design: true
  # for assets
  assets:
    - assets/
    - assets/icons/

# for generating launcher log
# run `flutter pub run flutter_launcher_icons : main`
flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/logo.png

# for generating assets object
flutter_gen:
  output: lib/gen